services:
  roborock-mqtt-bridge:
    image: ghcr.io/tobiaswaelde/roborock-mqtt-bridge:${IMAGE_TAG:-latest}
    restart: unless-stopped
    user: '${UID:-1000}:${GID:-1000}'
    environment:
      CORS_ORIGIN: '${CORS_ORIGIN:-*}'
      HOST: '${HOST:-0.0.0.0}'
      MAP_STORAGE_PATH: '${MAP_STORAGE_PATH:-/app/maps}'
      PORT: '${PORT:-3000}'
    volumes:
      - ./config:/app/config
      - ./maps:/app/maps
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
